name: Test All Anomalies with Continue on Error

on:
  workflow_dispatch:

permissions:
  checks: write
  contents: write
  packages: read

jobs:
  python-application-build:
    runs-on: ubuntu-latest
    name: Run build with anomalies
    steps:
      - name: Setup PSE
        uses: invisirisk/pse-action@dev-test
        with:
          api_url: "https://app.stage.invisirisk.com"
          app_token: ${{ secrets.IR_API_KEY_STAGE }}
          
      - uses: actions/checkout@v4

      - name: Use Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install downgraded package
        continue-on-error: true
        run: pip install requests==2.31.0

      - name: Install from unexpected source
        continue-on-error: true
        run: pip install numpy==1.9.3 --index-url https://test.pypi.org/simple/

      - name: Install typosquatted package
        continue-on-error: true
        run: curl -k -O https://files.pythonhosted.org/packages/83/5c/0627be4c9976d56b1217cb5187b7504e7fd7d3503f8bfd312a04077bd4f7/requestss-7.2.0-py2.py3-none-any.whl.metadata

      - name: Install with different checksum
        continue-on-error: true
        run: pip install --no-cache-dir --no-deps boto3==1.4.0 --index-url https://test.pypi.org/simple/

      - name: Contact new endpoint
        continue-on-error: true
        run: curl http://example.com/test

      - name: Run unusual command
        continue-on-error: true
        run: wget https://www.w3.org/TR/PNG/iso_8859-1.txt

      - name: Create unexpected file
        continue-on-error: true
        run: echo "Suspicious content" > suspicious2.txt

      - name: Simulate git push
        continue-on-error: true
        run: |
          git config --global user.name "ir-paras-oli"
          git config --global user.email "paras.oli@invisirisk.com"
          echo "Test" > test.txt
          git add test.txt
          git commit -m "Test commit"
          git push origin baseline || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: (Secrets check) Make API Request
        run: |
              curl -k -X POST https://api.github.com/endpoint \
              -d '{"name": "ghp_1234567890abcdef1234567890abcdef12345678", "description": "A description of my repository"}'

      - name: typosquatting requests
        run: |
           curl -k -O https://files.pythonhosted.org/packages/83/5c/0627be4c9976d56b1217cb5187b7504e7fd7d3503f8bfd312a04077bd4f7/requestss-7.2.0-py2.py3-none-any.whl.metadata

      - name: Simulate long-running task
        continue-on-error: true
        run: sleep 300 
        
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Cleanup PSE
        if: always()
        uses: invisirisk/pse-action@dev-test
        with:
          cleanup: "true"
