name: Python Project (short workflow STAGE)

on:
  workflow_dispatch:

permissions:
  checks: write
  contents: write
  packages: read

jobs:
  python-application-build:
    runs-on: ubuntu-latest
    name: Run build
    steps:
      - name: Setup PSE
        uses: invisirisk/pse-action@v1.0.20
        with:
          api_url: "https://app.stage.invisirisk.com"
          app_token: ${{ secrets.IR_API_KEY }}
          
      - uses: actions/checkout@v4

      - name: Use Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
       # run: pip install -r requirements.txt
        run: pip install --no-deps --trusted-host pypi.org --trusted-host files.pythonhosted.org requests33==0.1.0
      - run: pip install --no-deps --trusted-host pypi.org --trusted-host files.pythonhosted.org requests 
        
   #   - name: ðŸ˜ˆ Execute malicious script
    #    run: bash run_malicious_scripts.sh
        
      - name: Cleanup PSE
        if: always()
        uses: invisirisk/pse-action@v1.0.20
        with:
          cleanup: "true"
